# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-06 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181206_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='commit_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='down_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='up_num',
            field=models.IntegerField(default=0),
        ),
    ]
