# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-07 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181206_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default='/media/avatar/default.png', upload_to='avatar/'),
        ),
    ]
